/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  Erc20TokenInterface,
  Erc20TokenInterfaceInterface,
} from "../../../contracts/Ticket.sol/Erc20TokenInterface";

const _abi = [
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Erc20TokenInterface__factory {
  static readonly abi = _abi;
  static createInterface(): Erc20TokenInterfaceInterface {
    return new Interface(_abi) as Erc20TokenInterfaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): Erc20TokenInterface {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as Erc20TokenInterface;
  }
}
