/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        primary: ['var(--font-dark-grotesk)'],
        inter: ['var(--font-inter)'],
        'n-montreal': ['var(--font-neue-montreal)'],
        craftwork: ['var(--font-craft)'],
        roboto: ['var(--font-roboto)'],
        merriweather: ['var(--font-merriweather)'],
        'general-sans': ['var(--font-general-sans)'],
        playfair: ['var(--font-playfair)'],
      },
      colors: {
        'settley-bg': '#fbf8f1', // Keep this as it matches the visual beige
        'settley-text': 'oklch(0.55 0.02 265)', // Ref Link Color
        'settley-text-hover': 'oklch(0.2 0.02 265)', // Ref Link Hover
        'settley-primary': 'oklch(0.2 0.05 265)', // Ref Primary (Sign Up bg, Login border)
        navy: '#272343',
        'light-grey': '#F4F4F4',
        'medium-grey': '#CBCBCB',
        'dark-grey': '#515151',
        yellow: '#FFD803',
        cream: '#FFFBE5',
        'light-green': '#DCF1BF',
        'light-red': '#F7D9D9',
        'primary-orange': '#FC6720',
        // Design System Colors
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#45464c',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: '#76777d',
        'outline-variant': '#c6c6cd',
        'surface-tint': '#575e70',
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#151b2b',
        'on-primary-container': '#7d8497',
        'inverse-primary': '#c0c6db',
        secondary: '#625e52',
        'on-secondary': '#ffffff',
        'secondary-container': '#e8e2d2',
        'on-secondary-container': '#686458',
        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#1b1c15',
        'on-tertiary-container': '#85847a',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#dce2f8',
        'primary-fixed-dim': '#c0c6db',
        'on-primary-fixed': '#151b2b',
        'on-primary-fixed-variant': '#404758',
        'secondary-fixed': '#e8e2d2',
        'secondary-fixed-dim': '#ccc6b7',
        'on-secondary-fixed': '#1e1c12',
        'on-secondary-fixed-variant': '#4a473b',
        'tertiary-fixed': '#e4e3d7',
        'tertiary-fixed-dim': '#c8c7bc',
        'on-tertiary-fixed': '#1b1c15',
        'on-tertiary-fixed-variant': '#47473f',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        'surface-variant': '#d3e4fe',
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'container-max': '1280px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'stack-sm': '8px',
        'stack-md': '24px',
        'stack-lg': '48px',
      },
      clipPath: {
        hero: 'polygon(0 0, 100% 0, 92% 100%, 0% 100%)',
      },
    },
  },
  plugins: [],
};
