/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        primary: ['var(--font-dark-grotesk)'],
        inter: ['var(--font-inter)'],
        'n-montreal': ['var(--font-neue-montreal)'],
        craftwork: ['var(--font-craft)'],
        roboto: ['var(--font-roboto)'],
        playfair: ['var(--font-playfair)'],
      },
      colors: {
        'settley-bg': '#fbf8f1',
        'settley-text': 'oklch(0.55 0.02 265)',
        'settley-text-hover': 'oklch(0.2 0.02 265)',
        'settley-primary': 'oklch(0.2 0.05 265)',
        navy: '#272343',
        'light-grey': '#F4F4F4',
        'medium-grey': '#CBCBCB',
        'dark-grey': '#515151',
        yellow: '#FFD803',
        cream: '#FFFBE5',
        'light-green': '#DCF1BF',
        'light-red': '#F7D9D9',
        surface: '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#45464c',
        outline: '#76777d',
        'outline-variant': '#c6c6cd',
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#151b2b',
        'secondary-fixed': '#e8e2d2',
        danger: '#ba1a1a',
      },
    },
  },
  plugins: [],
};
