/* eslint-disable no-console */
import { AxiosError } from 'axios';
import { toast } from 'sonner';

import { showLogger } from '../constants/env';

/**
 * A logger function that will only logs on development
 * @param object - The object to log
 * @param comment - Autogenerated with `lg` snippet
 */

export default function logger(object: unknown, comment?: string): void {
  if (!showLogger) return;

  console.log(
    '%c ============== INFO LOG \n',
    'color: #22D3EE',
    `${typeof window !== 'undefined' && window?.location.pathname}\n`,
    `=== ${comment ?? ''}\n`,
    object
  );
}

export const errorLogger = (error: unknown) => {
  if (error instanceof AxiosError) {
    logger({ error: error.response?.data }, 'Axios Error');
    toast.error(error.response?.data ?? 'Server Error');
  }
};
