/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Erc20TokenInterface } from "./Erc20TokenInterface";
export type { SettleyTicket } from "./SettleyTicket";
